version: "3.8"

services:
  db01:
    build: .
    container_name: DB01
    entrypoint: bash entrypoint.sh
#    command: postgres -c config-file=/etc/postgresql.conf
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db01/postgresql.conf:/etc/postgresql.conf
      - ./db01/pg_hba.conf:/etc/postgresql/9.5/main/pg_hba.conf
      - ./backups/data:/var/lib/postgresql/9.5/main
      - ./backups:/backups
