version: "3.8"

services:
  db01:
    image: "postgres:9.5"
    container_name: DB01
    environment:
      - POSTGRES_USER=t2elzeth
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    volumes:
#      - postgres_data:/var/lib/postgresql/data/
      - ./db01/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    
  db02:
    image: "postgres:9.5"
    container_name: DB02
    environment:
      - POSTGRES_USER=t2elzeth
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
